apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-backup
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-backup
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-backup
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: grafana-backup
    namespace: monitoring
roleRef:
  kind: Role
  name: grafana-backup
  apiGroup: rbac.authorization.k8s.io
