---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCCo5yPgiMi6weYuzHp9WIiZozfX+229s2MY9cbmEq+GwBY/aBFr0DLQhoTBT5Wc9dWyJRUZBALZs8FE0mf028OtzdkyfFkxzeN9i22TSXygjzw/b/QiJomWc03fgG+8QTltIiONaxyOgN5FXcX2xoZdjNnVRIzwJ5N27pxZVl6xi725OXiXdf4MKcdztUknQx7CxGUY+EUHV9NfLjVsZN7Ee2t9AYwBIm/Z2I7nuOkrpauXOGhEZIdfStBuksw5h4HcfxIeTPzQPbJHo5A/cH0CTtprcBzRwMEzw/amZRA8W0FboWrm0buS02B+zZyOlHnYV/xn3NvR2miQPMMBM5QJf4/dKYq8lue4WF96R6adZbjpUyv+TesRwFyyUwGK+5HwhUCh5zXXPH8op6Hdm9EdUjF20U1xnqu7Q7Rnp2ONVT17INxqGd43XvJKj5/tR/UC0qTPfk+PbtUtGF8qVt+i9nEqCFsi+c1N01hNosJrQeWGNijI8AIkj4hwTzIH/IUHO1bDPUncg6XAh96g8kQ+A72MYeUfHay0bRsr+y7yJypH6R4wwtZoRmaNkHpAlqR/+a6q6i+HHLGuUFJ/Z3M+7ZjJiPB9SPXKay2tQ34YkKgmWdUvHTE1Qo4cdKA9WQJQKU2h3Nxe5jysMtdzlbARsn1bwtwgWJfL2FPs90tQUHd1CeIkschPgmRol1ezBKatqfGnGIfkSo33KHh7Q==
    admin-user: AgAQr3UajeSdZXI89BkfwRrSioieadb326r7RYQxk6is9QNYdLXnHTJLpCGzxWJhmLR4gkmkx3z7+j4jo2T5nBN79XIdCLrmOEIiTWE4gvCcsHDVmnCv/i6wj6bx0GsWEB8OHn8snjdYrFHrgbuKow/SjrRZQfYSyqjXpVuhVf0YMwNcR/utwSYy6xql895mzJg9QojJYC0zJr8UXtW1r41SavU0cUE5z1zNOfapiz6Y22rN88oxTBE+9Fqh6Cf1FDOjvzQXG/FWfh9Y8WgBKf3V+CYhiHDyP+WoB13k8grkbrNZe6qTc3mSnMduP/VQv9vliY6pF9RXvX6miUBtZs9bsuoDe3l2FGIHwYIV3XeCx4bcE00m0/DDw4s2N7M6ps7BtvG2b2uMEq6LMMzQIKtJVBkZTe6fgJESJRMPsYd3t2XDQdxKGM73ezL40/wjTntfw8NiA1D+6Dl2fg4Gve4yzQ7zRSZNxLez9UHA5PcHpO4Hjvu51UAOCK4Ntcgx/s7gzpXGIBqQP7z5v1Ng1xtlvKLTBr0Q6BN1w4uuxLACRsXqawjvujXHzJQAd4ibKcRUQ8hBfg5bv0mjFOYXjFjhb/iiSQaYsanHRGO5aGWlaF1yl4LfS6bFgNJqPbssjOCkmJyQVI37KHZvmcI4JNuDJDoCzgMsGGkUcRnausBZ/AXnnV7DBHsb9ctBwaL/a+m9OeNv2A==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
